self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - azure
    - cloudflare
    - gh-aw
    - local-model
    - local-macrunner-qwenollama
    - macos-local
    - qwen2-5-0-5b

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
# The following configurations are available.
#
# "ignore" is an array of regular expression patterns. Matched error messages
# are ignored. This is similar to the "-ignore" command line option.
paths:
  .github/workflows/*.lock.yml:
    ignore:
      - 'shellcheck reported issue in this script: SC2016'
      - 'shellcheck reported issue in this script: SC2086'
      - 'unexpected key "queue" for "concurrency" section'
